./train.py --config DATA.BASEDIR=./data MODE_FPN=True MODE_MASK=False \
	"DATA.VAL=('val',)"  "DATA.TRAIN=('train',)" \
	TRAIN.BASE_LR=1e-3 TRAIN.EVAL_PERIOD=0 "TRAIN.LR_SCHEDULE=[1000]" \
	"PREPROC.TRAIN_SHORT_EDGE_SIZE=[600,1200]" TRAIN.CHECKPOINT_PERIOD=1
